# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
  pull_request:
    branches: [ "master" ]
  schedule:
  - cron: "0 2 * * SUN"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
  
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test jacocoTestReport
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: build/reports/jacoco

  depcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dependencyCheckAnalyze
      - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: Dependency Vulnerability Report
          path: build/reports/dependency-check-report.html
